---
- hosts: 172.31.95.30
  become: yes
  vars:
    req_java: java-1.8.0-openjdk
    set_java: jre-1.8.0-openjdk
    req_tomcat_ver: 8.5.75
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-{{req_tomcat_ver.split('.')[0]}}/v{{req_tomcat_ver}}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz
  roles:
    - role: tomcat4all

