---
- name: Downloading tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.75/bin/apache-tomcat-8.5.75.tar.gz
    dest: /usr/local
- name: Extracting tomcat
  unarchive:
    src: "/usr/local/apache-tomcat-8.5.75.tar.gz"
    dest: /usr/local
    remote_src: yes
- name: Renaming file
  command: mv /usr/local/apache-tomcat-8.5.75 /usr/local/tomcat
- name: Starting the tomcat server
  shell: nohup /usr/local/tomcat/bin/startup.sh &
- name: Deploying War file
  copy:
    src: /tempwar/SampleWebApp.war    #source also in Nodeserver,need to practice from different sources(github,from another server)
    dest: /usr/local/tomcat/webapps/
